version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src  # Le code source
    ports:              # <--- ATTENTION : 'ports' est alignÃ© avec 'volumes' (pas dedans !)
      - "8501:8501"     # Le port pour Streamlit
    command: python -c "import time; print('App is running...'); time.sleep(3600)"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: fastfood_user
      POSTGRES_PASSWORD: fastfood_password
      POSTGRES_DB: fastfood_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: