version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "8501:8501"
    command: python -c "import time; print('App running...'); time.sleep(3600)"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: fastfood_user
      POSTGRES_PASSWORD: fastfood_password
      POSTGRES_DB: fastfood_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- AJOUT DE GRAFANA ICI ---
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # Le port standard de Grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Mot de passe par d√©faut
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:  # <--- N'oublie pas d'ajouter ce volume en bas !